name: voice_cleaner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  audio_waveforms: ^2.0.2
  audioplayers: ^6.6.0
  ffmpeg_kit_flutter_new: ^3.0.0
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_nnnoiseless: ^1.0.1
  path_provider: ^2.1.5
  record: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/sample.aac
  
flutter_icons:
  image_path: "assets/images/logo2.png"
  android: true
  ios: true
  linux: true
